---
AllCops:
  Exclude:
    - vendor/**/*
    - lib/yard/parser/ruby/legacy/irb/slex.rb
    - lib/yard/parser/ruby/legacy/ruby_lex.rb
    - lib/yard/server/http_utils.rb
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2
Bundler/GemFilename:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false
Layout/ArrayAlignment:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  AutoCorrect: true
  Exclude:
    - spec/**/*.rb
  Max: 120
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ParameterAlignment:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Lint/ConstantDefinitionInBlock:
  Exclude:
    - benchmarks/**/*.rb
    - docs/**/*.rb
    - spec/**/*.rb
Lint/DuplicateMethods:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/RedundantSplatExpansion:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Lint/UselessConstantScoping:
  Enabled: false
Metrics:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Performance:
  Exclude:
    - spec/**/*.rb
Security/Eval:
  Exclude:
    - benchmarks/**/*.rb
    - spec/**/*.rb
Security/MarshalLoad:
  Enabled: false
Style/BlockComments:
  Exclude:
    - benchmarks/*.rb
Style/CaseEquality:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/EvalWithLocation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/FileRead:
  Enabled: false
Style/FileWrite:
  Enabled: false
Style/FormatString:
  EnforcedStyle: percent
Style/FormatStringToken:
  Enabled: false
Style/GlobalVars:
  Exclude:
    - benchmarks/**/*.rb
    - spec/**/*.rb
Style/GuardClause:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/IfWithBooleanLiteralBranches:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - docs/**/*.rb
    - benchmarks/**/*.rb
    - spec/**/*
    - templates/**/*
    - lib/yard/templates/**/*
Style/MultilineIfModifier:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/OpenStructUse:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%I': ()
    '%W': ()
    '%i': ()
    '%w': ()
Style/PerlBackrefs:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/Semicolon:
  AllowAsExpressionSeparator: true
Style/SingleLineBlockParams:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/WhenThen:
  Enabled: false
Style/WordArray:
  Enabled: false
plugins:
  - rubocop-rake
  - rubocop-performance
