plugins:
  - rubocop-rake
  - rubocop-performance
AllCops:
  TargetRubyVersion: 2.0
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - vendor/**/*
    - lib/yard/parser/ruby/legacy/irb/slex.rb
    - lib/yard/parser/ruby/legacy/ruby_lex.rb
    - lib/yard/server/http_utils.rb
Metrics:
  Enabled: false
Performance:
  Exclude:
    - spec/**/*.rb
Gemspec/RequireMFA:
  Enabled: false
Layout/LineLength:
  AutoCorrect: true
  Max: 120
  Exclude:
    - spec/**/*.rb
Naming/MethodParameterName:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/Semicolon:
  AllowAsExpressionSeparator: true
Style/Documentation:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Style/NumericPredicate: # ruby 1.8/1.9 do not have positive?/negative?
  EnforcedStyle: comparison
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/DotPosition:
  EnforcedStyle: trailing
Style/FormatString:
  EnforcedStyle: percent
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Style/SafeNavigation:
  Enabled: false # not supported in 1.8...2.1
Style/DocumentDynamicEvalDefinition: # not helpful
  Enabled: false
Style/OpenStructUse:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - docs/**/*.rb
    - benchmarks/**/*.rb
    - spec/**/*
    - templates/**/*
    - lib/yard/templates/**/*
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "()"
    "%W": "()"
    "%i": "()"
    "%I": "()"
Style/MultilineIfModifier: # autocorrect usually fails
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/GuardClause: # does not provide much value
  Enabled: false
Style/IfWithBooleanLiteralBranches: # this isn't reliable
  Enabled: false
Lint/DuplicateMethods:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Exclude:
    - benchmarks/**/*.rb
    - docs/**/*.rb
    - spec/**/*.rb
Style/FormatStringToken:
  Enabled: false
Lint/UselessConstantScoping:
  Enabled: false
Lint/SuppressedException:
  Enabled: false
Bundler/GemFilename:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Naming/AccessorMethodName: # this creates breaking changes in the API
  Enabled: false
Naming/PredicateName: # this creates breaking changes in the API
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Lint/MissingSuper: # this doesn't exist in 1.8/1.9
  Enabled: false
Style/MissingRespondToMissing: # this doesn't exist in 1.8/1.9
  Enabled: false
Style/Lambda: # not supported in 1.8
  Enabled: false
Style/EachWithObject: # not supported in 1.8
  Enabled: false
Layout/ParameterAlignment: # does not work correctly with subsequent block
  Enabled: false
Layout/ArrayAlignment: # does not support indentation
  Enabled: false
Layout/HashAlignment: # does not support indentation
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Style/EvalWithLocation:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/SingleLineBlockParams:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/WhenThen:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/BlockComments:
  Exclude:
    - benchmarks/*.rb
Style/CaseEquality:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/GlobalVars:
  Exclude:
    - benchmarks/**/*.rb
    - spec/**/*.rb
Style/StderrPuts:
  Enabled: false
Style/FileWrite:
  Enabled: false
Style/FileRead:
  Enabled: false
Lint/RedundantSplatExpansion:
  Enabled: false
Security/Eval:
  Exclude:
    - benchmarks/**/*.rb
    - spec/**/*.rb
Security/MarshalLoad:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
